dateModified: 1721273066
email:
  fromEmail: guilleozan25@gmail.com
  fromName: marina.test
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    5dfe7698-caeb-43e1-b4b3-18047d11d635: marina.test # marina.test
    66c8c5ae-2fa8-4e37-8021-b19b4c88216f: marina.test # marina.test
system:
  edition: solo
  live: true
  name: marina.test
  schemaVersion: 5.0.0.21
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
